'use client'

import { useEffect, useState } from 'react'

import Navbar from '@/components/layout/Navbar'

import {
    AnalyzeResponse,
} from '@/types/analysis'

import IndustryMatchCard from '@/components/dashboard/IndustryMatchCard'
import IndustryProbabilityCard from '@/components/dashboard/IndustryProbabilityCard'
import SkillGapCard from '@/components/dashboard/SkillGapCard'
import LearningPathCard from '@/components/dashboard/LearningPathCard'
import ExplainableCard from '@/components/dashboard/ExplainableCard'
import SummaryCard from '@/components/dashboard/SummaryCard'

export default function DashboardPage() {



    const [result, setResult] =
        useState<AnalyzeResponse | null>(
            null
        )

    useEffect(() => {

        const saved =
            localStorage.getItem(
                'analysis_result'
            )

        if (saved) {
            setResult(
                JSON.parse(saved)
            )
        }

    }, [])

    if (!result) {
        return (
            <>
                <Navbar />

                <main className="container-custom pt-32">
                    <h1 className="text-3xl font-bold text-white">
                        No Analysis Found
                    </h1>

                    <p className="mt-4 text-slate-400">
                        Please run an analysis first.
                    </p>
                </main>
            </>
        )
    }

    const topIndustry =
        result.data.industry_predictions[0]

    const recommendedSkillsCount =
        result.data.recommended_skills.length

    const learningLevelsCount =
        result.data.learning_path.filter(
            (item) =>
                item.skills.length > 0
        ).length

    return (
        <>
            <Navbar />

            <main
                className="
                    container-custom
                    pt-32
                    pb-20
                "
            >
                <h1
                    className="
                        text-4xl
                        font-bold
                        text-white
                    "
                >
                    Your Career Intelligence Report
                </h1>

                <p
                    className="
                        mt-3
                        text-slate-400
                    "
                >
                    Industry prediction, skill gap analysis,
                    and personalized learning recommendations
                    generated by SkillMatch AI.
                </p>

                <div className="mt-10 grid gap-8">

                    <SummaryCard
                        topIndustry={
                            topIndustry.industry
                        }
                        confidence={
                            topIndustry.probability
                        }
                        recommendedSkills={
                            recommendedSkillsCount
                        }
                        learningLevels={
                            learningLevelsCount
                        }
                    />

                    <IndustryMatchCard
                        industry={
                            topIndustry.industry
                        }
                        probability={
                            topIndustry.probability
                        }
                    />

                    <IndustryProbabilityCard
                        industries={
                            result.data
                                .industry_predictions
                        }
                    />

                    <SkillGapCard
                        skills={
                            result.data
                                .recommended_skills
                        }
                    />

                    <LearningPathCard
                        learningPath={
                            result.data
                                .learning_path
                        }
                    />

                    <ExplainableCard
                        skills={
                            result.data
                                .recommended_skills
                        }
                    />

                </div>
            </main>
        </>
    )
}